services:
  - type: web
    name: locagram
    env: node
    buildCommand: npm install && npm run build
    startCommand: npm start
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 5000
      - key: SESSION_SECRET
        generateValue: true
    healthCheckPath: /
    autoDeploy: true
    plan: free 